apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: nhc-kube-rbac-proxy-tls
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: metrics
    app.kubernetes.io/name: node-healthcheck-operator
  name: node-healthcheck-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/name: node-healthcheck-operator
status:
  loadBalancer: {}
