apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: metrics
  annotations:
      service.beta.openshift.io/serving-cert-secret-name: node-healthcheck-tls
  name: controller-manager-metrics-service
  namespace: system
