apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: nhc-kube-rbac-proxy-tls
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: metrics
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
